version: '3.8'

services:
  whatsapp-api:
    build: .
    container_name: whatsapp-api
    ports:
      - "3006:3006"
    environment:
      - PORT=3006
      - NODE_ENV=production
    volumes:
      # CRÍTICO: Monta el directorio de sesiones como volumen persistente
      - ./sessions:/app/sessions
      # Alternativa con named volume:
      # - whatsapp-sessions:/app/sessions
    restart: unless-stopped
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3006/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  whatsapp-network:
    driver: bridge

# Opción con named volume (recomendado para producción)
# volumes:
#   whatsapp-sessions:
#     driver: local

